//! Conservative single-frame expression-quality fusion.
//!
//! The frozen head combines the raw outputs of two HSEmotion classifiers with
//! the existing 38 non-eye Blendshape coefficients. It was fitted on 105
//! geometrically reliable expression-labelled observations plus 38 explicit
//! calibration observations. Another 125 reliable manual 3-5 star photos are
//! one-way positive guards only; their lower ratings are not expression labels.
//!
//! Leave-one-capture-group-out accuracy/AUC were 81.0%/0.876 on the 105-image
//! set and 82.1%/0.963 on the original 28-image calibration set. The newest
//! ten observations were used for model selection and calibration, not blind
//! testing, so this remains a low-confidence macOS Debug calibration.

use super::{EXPRESSION_QUALITY_REASON, ExpressionDescriptor, ExpressionEvidence};
use crate::features::smart_culling::expression_quality_poc::ExpressionQualityModelOutputs;

const FEATURE_COUNT: usize = 56;
const MAX_CALIBRATION_CONFIDENCE: f32 = 0.49;

// Exact order: HSE MTL[0..10], HSE VGAF[0..8], then
// log1p(100 * ExpressionDescriptor.non_eye_blendshapes[0..38]). The frozen
// values are generated by model_assets/hsemotion_poc/train_fusion.py and
// audited in FUSION_CALIBRATION.json.
const FEATURE_MEANS: [f64; FEATURE_COUNT] = [
    -1.4854888919662763,
    1.0009138150778891,
    -1.6766804562998818,
    -0.8759941252899337,
    2.4482433026382973,
    0.7796011490004879,
    -0.5902302493373831,
    1.0463875456341913,
    0.2769416999462601,
    0.1869713670307106,
    -2.5444446014878634,
    0.6752948252210668,
    -3.4424306230319965,
    -1.9599332139938028,
    2.816434903474121,
    1.4287824791211348,
    -0.43288794868475905,
    1.3347753744858961,
    0.0005986343374855305,
    1.6351906958036078,
    1.6185600865500818,
    2.3004080450261175,
    2.2334494981017396,
    1.912187532832734,
    0.018681155834620867,
    0.0001151735577415492,
    0.0000788609711064566,
    0.03839647705254897,
    0.1495108258082974,
    1.5020849771597813,
    0.06140075370972331,
    0.3857959706086279,
    1.0407440735387579,
    0.7741483960900947,
    0.044714122099203224,
    0.057037237218753714,
    0.9597966686640985,
    0.29441768272918567,
    0.5853610189638784,
    0.690450009485122,
    2.0194139133029587,
    1.8456966886671402,
    1.5870957977860125,
    0.20932712144628499,
    0.7420099612162117,
    0.8465680128908233,
    1.2018277262292316,
    1.4001941188578477,
    2.359048290288357,
    2.302794870507196,
    0.3997658746921578,
    0.6784480425740052,
    1.3283886822294182,
    1.3081409144725473,
    0.00023641617936060206,
    0.00020761113118114612,
];

const FEATURE_STDS: [f64; FEATURE_COUNT] = [
    1.427985016295507,
    2.351676100593651,
    1.5228014049051433,
    2.4491049890515018,
    3.3009054031330165,
    1.6355578804793947,
    1.7525609246991063,
    2.5125703307540705,
    0.45830893299762765,
    0.3641103085611918,
    3.281602104038266,
    3.072371464465357,
    3.5519471240725147,
    4.1286002207532375,
    2.877089254777095,
    2.7164178184466388,
    2.9436085197407285,
    2.856732506111063,
    0.000704218628738662,
    1.3479614071279695,
    1.3463295804910274,
    1.4447778948102634,
    1.3672782018404472,
    1.227806869161965,
    0.03097099621488636,
    0.00013692335398573084,
    0.00008872147223152528,
    0.05797395390235221,
    0.20870297492953294,
    1.2557486956895294,
    0.11152562641417221,
    0.3459231189283613,
    0.5398982835992605,
    0.5503586410343083,
    0.13902007975285555,
    0.1927260850482716,
    0.9277950702670192,
    0.35270756984762075,
    0.7935733953914793,
    0.9537047091996926,
    0.981916641176556,
    0.9550182809409339,
    1.3230357428828483,
    0.4058730006963047,
    0.8043379709981797,
    0.725768492062938,
    1.1800946023812897,
    0.504903869757091,
    1.7890022596753594,
    1.7653326453125326,
    0.5018106955185188,
    0.7535122286519482,
    1.5996636449031494,
    1.5778007907629927,
    0.0002508976531843984,
    0.0002714076522657786,
];

const WEIGHTS: [f64; FEATURE_COUNT] = [
    0.02228222198573398,
    -0.04878720104450058,
    -0.4045584937467349,
    -0.16249094260851185,
    0.16070120766522802,
    0.14324760600834863,
    0.14691583923327828,
    -0.05504692255629948,
    0.1067988837770164,
    -0.15956780220892716,
    -0.19713610509308696,
    -0.12386891376224789,
    -0.40649289682022993,
    -0.2834787021903942,
    0.20966900613528297,
    -0.014443261135796165,
    -0.09837478606984544,
    -0.157384374691578,
    0.02329884410627164,
    0.26274629617211737,
    0.1789934833835503,
    -0.19982252269111223,
    -0.07629639825295857,
    0.05054130009582563,
    -0.10343807937011142,
    0.09971667917218988,
    -0.20208883582803183,
    0.04577648019231532,
    0.0026943640240824963,
    -0.22834205854339246,
    -0.017593232841109356,
    -0.1463463517268625,
    -0.2568792490692916,
    0.01836620170577862,
    -0.06352194521259634,
    0.057362934770669255,
    -0.11482236412565872,
    -0.37986537599381576,
    0.05473482455459015,
    0.07808683340337946,
    0.003577571747922181,
    0.03499936763003459,
    0.00829791473760545,
    -0.02768442089005886,
    -0.08789156395043342,
    -0.033198721234791964,
    0.307786978452375,
    0.12632120502935007,
    -0.012683361633636666,
    0.02039874236427452,
    -0.10604675901222678,
    0.09416998589993388,
    -0.05304064927151535,
    0.0030330376898936515,
    -0.018055929380354933,
    0.11246260447073712,
];

const BIAS: f64 = -0.32937729556950873;

pub(super) fn assess_single_frame(
    descriptor: &ExpressionDescriptor,
    model_outputs: &ExpressionQualityModelOutputs,
) -> ExpressionEvidence {
    if !descriptor.is_reliable() {
        return ExpressionEvidence::unavailable("expression_frame_evidence_unreliable");
    }
    let Some(quality_score) = usable_probability(descriptor, model_outputs) else {
        return ExpressionEvidence::unavailable("expression_quality_model_output_invalid");
    };

    let center_separation = ((quality_score - 0.5).abs() * 2.0).clamp(0.0, 1.0);
    let calibration_confidence = 0.25 + 0.24 * center_separation;
    ExpressionEvidence {
        state: "scored",
        quality_score: Some(quality_score as f32),
        confidence: (descriptor.reliability() * calibration_confidence as f32)
            .clamp(0.0, MAX_CALIBRATION_CONFIDENCE),
        reason: EXPRESSION_QUALITY_REASON,
    }
}

fn usable_probability(
    descriptor: &ExpressionDescriptor,
    model_outputs: &ExpressionQualityModelOutputs,
) -> Option<f64> {
    let values = model_outputs
        .mtl
        .iter()
        .chain(&model_outputs.vgaf)
        .map(|value| f64::from(*value))
        .chain(
            descriptor
                .non_eye_blendshapes()
                .iter()
                .map(|value| (1.0 + 100.0 * f64::from(*value)).ln()),
        );
    let mut count = 0usize;
    let logit = values
        .zip(FEATURE_MEANS)
        .zip(FEATURE_STDS)
        .zip(WEIGHTS)
        .try_fold(BIAS, |sum, (((value, mean), std), weight)| {
            count += 1;
            value
                .is_finite()
                .then_some(sum + ((value - mean) / std) * weight)
        })?;
    if count != FEATURE_COUNT || !logit.is_finite() {
        return None;
    }
    let logit = logit.clamp(-40.0, 40.0);
    Some(1.0 / (1.0 + (-logit).exp()))
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use super::*;
    use crate::features::smart_culling::expression::NON_EYE_BLENDSHAPE_NAMES;

    fn descriptor(yaw: f32, eye_score: f32) -> ExpressionDescriptor {
        let mut scores = NON_EYE_BLENDSHAPE_NAMES
            .into_iter()
            .map(|name| (name, 0.0))
            .collect::<BTreeMap<_, _>>();
        scores.insert("eyeBlinkLeft", eye_score);
        scores.insert("eyeBlinkRight", eye_score);
        ExpressionDescriptor::from_face_motion(&scores, 0.0, Some(0.0), Some(yaw), Some(0.01), 0.99)
            .unwrap()
    }

    fn outputs(value: f32) -> ExpressionQualityModelOutputs {
        ExpressionQualityModelOutputs {
            mtl: [value; 10],
            vgaf: [value; 8],
        }
    }

    #[test]
    fn fusion_emits_a_finite_continuous_low_confidence_score() {
        let evidence = assess_single_frame(&descriptor(0.0, 0.0), &outputs(0.0));

        assert_eq!(evidence.state, "scored");
        assert!(
            evidence
                .quality_score
                .is_some_and(|score| score.is_finite() && (0.0..=1.0).contains(&score))
        );
        assert!(evidence.confidence > 0.0);
        assert!(evidence.confidence <= MAX_CALIBRATION_CONFIDENCE);
        assert_eq!(evidence.reason, EXPRESSION_QUALITY_REASON);
    }

    #[test]
    fn eye_blendshape_coefficients_cannot_change_the_fusion_score() {
        let baseline = assess_single_frame(&descriptor(0.0, 0.0), &outputs(0.0));
        let changed_eyes = assess_single_frame(&descriptor(0.0, 1.0), &outputs(0.0));

        assert_eq!(baseline, changed_eyes);
    }

    #[test]
    fn unreliable_geometry_stays_unknown_before_model_fusion() {
        let evidence = assess_single_frame(&descriptor(40.0, 0.0), &outputs(0.0));

        assert_eq!(evidence.state, "unknown");
        assert_eq!(evidence.quality_score, None);
        assert_eq!(evidence.reason, "expression_frame_evidence_unreliable");
    }

    #[test]
    fn non_finite_model_output_fails_closed_to_unknown() {
        let evidence = assess_single_frame(&descriptor(0.0, 0.0), &outputs(f32::NAN));

        assert_eq!(evidence.state, "unknown");
        assert_eq!(evidence.quality_score, None);
        assert_eq!(evidence.reason, "expression_quality_model_output_invalid");
    }
}
